# Project information
site_name: "Samvaad"
site_description: "Conversations with Shri A Nagraj"
site_author: "Achal Agrawal"
site_url: "https://samvaad.utsv.in"

# Configuration
extra_css:
  - stylesheets/extra.css
theme:
  name: "material"
  features:
    - navigation.footer
  language: "en"
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: "Roboto"

# Customization
extra:
  generator: false
  manifest: "manifest.json"

plugins:
  - search

#PWA Config
use_directory_urls: false
scope: "./"
version: 0.0.5
